version: "3.9"

services:
    fast-arq-app:
        image: billaram/fast-arq-app:latest
        container_name: fast-arq-app
        environment:
            REDIS_ARQ_HOST: redis
        ports:
            - 8080:80

    fast-arq-worker:
        image: billaram/fast-arq-worker:latest
        container_name: fast-arq-worker
        environment:
            REDIS_ARQ_HOST: redis
    
    redis:
        image: redis
        container_name: redis
        expose:
          - 6379
        ports:
          - 6379:6379
    